"""empty message

Revision ID: 55a47e2cfca1
Revises: 1b7d5505a4b6
Create Date: 2025-01-04 07:27:48.317767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '55a47e2cfca1'
down_revision: Union[str, None] = '1b7d5505a4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatsession', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatsession', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
